"""
report_generator.py — turns the day's matched news + trade setups
into a markdown report, and a matching JSON file for the local
dashboard to consume.
"""
from __future__ import annotations
import json
import math
import os
from datetime import datetime, timezone
from typing import List

from technical_analysis import TradeSetup

DISCLAIMER = (
    "> ⚠️ **Not financial advice.** These levels are generated by a rules-based "
    "system (ATR-based stop, fixed risk:reward target, news-sentiment bias). "
    "No entry/stop/target from any system is \"perfect\" — always size positions "
    "for the possibility of loss and confirm setups yourself before trading."
)


def _fmt(n: float | None, decimals: int = 5) -> str:
    return f"{n:.{decimals}f}" if n is not None else "—"


def render_report(setups: List[TradeSetup], headline_count: int, matched_count: int) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Daily Financial News Scan — {now}",
        "",
        DISCLAIMER,
        "",
        f"Scanned **{headline_count}** headlines, found **{matched_count}** relevant to the watchlist, "
        f"generated **{len(setups)}** trade setups with a clear directional bias.",
        "",
    ]

    if not setups:
        lines.append("No high-conviction setups today — sentiment was neutral or mixed across the watchlist.")
        return "\n".join(lines)

    # sort: HIGH confidence first
    order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
    setups_sorted = sorted(setups, key=lambda s: order.get(s.confidence, 3))

    lines.append("| Instrument | Bias | Confidence | Entry | Stop Loss | Take Profit | R:R |")
    lines.append("|---|---|---|---|---|---|---|")
    for s in setups_sorted:
        lines.append(
            f"| {s.ticker} | {s.bias} | {s.confidence} | {_fmt(s.entry)} | "
            f"{_fmt(s.stop_loss)} | {_fmt(s.take_profit)} | 1:{s.risk_reward:.1f} |"
        )

    lines.append("")
    lines.append("## Details")
    for s in setups_sorted:
        lines.append(f"\n### {s.ticker} — {s.bias} ({s.confidence} confidence)")
        lines.append(f"- Last close: {_fmt(s.last_close)}  |  ATR({14}): {_fmt(s.atr)}")
        lines.append(f"- Recent swing high/low: {_fmt(s.swing_high)} / {_fmt(s.swing_low)}")
        lines.append(f"- Trend aligned with news bias: {'Yes' if s.trend_aligned else 'No'}")
        if s.notes:
            for n in s.notes:
                lines.append(f"- Note: {n}")

    return "\n".join(lines)


def save_report(content: str, path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _safe(n: float | None) -> float | None:
    """None/NaN-safe float for JSON (JSON has no NaN)."""
    if n is None or (isinstance(n, float) and math.isnan(n)):
        return None
    return n


def save_json(setups: List[TradeSetup], headline_count: int, matched_count: int,
              path: str, date_str: str) -> None:
    """Write a structured JSON version of the report for the dashboard."""
    payload = {
        "date": date_str,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "headline_count": headline_count,
        "matched_count": matched_count,
        "setups": [
            {
                "ticker": s.ticker,
                "bias": s.bias,
                "confidence": s.confidence,
                "entry": _safe(s.entry),
                "stop_loss": _safe(s.stop_loss),
                "take_profit": _safe(s.take_profit),
                "risk_reward": s.risk_reward,
                "last_close": _safe(s.last_close),
                "atr": _safe(s.atr),
                "swing_high": _safe(s.swing_high),
                "swing_low": _safe(s.swing_low),
                "trend_aligned": s.trend_aligned,
                "notes": s.notes,
            }
            for s in setups
        ],
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def update_index(reports_dir: str) -> None:
    """Regenerate reports/index.json — the list of available report dates
    the dashboard reads to populate its date picker."""
    dates = sorted(
        fn[:-5] for fn in os.listdir(reports_dir)
        if fn.endswith(".json") and fn != "index.json"
    )
    index_path = os.path.join(reports_dir, "index.json")
    with open(index_path, "w", encoding="utf-8") as f:
        json.dump({"dates": dates}, f, indent=2)


if __name__ == "__main__":
    dummy = [TradeSetup(
        ticker="EURUSD=X", bias="BULLISH", last_close=1.1612, atr=0.0029,
        swing_high=1.1621, swing_low=1.1429, trend_aligned=True,
        entry=1.1612, stop_loss=1.1429, take_profit=1.1979,
        risk_reward=2.0, confidence="HIGH", notes=["Sample note"],
    )]
    print(render_report(dummy, headline_count=120, matched_count=8))
